### PR TITLE
Olivier is looking a pair to work on his project

### PR DESCRIPTION
**Pull request by toch**
Does someone could help @nicefiction?

### CODE REVIEW

**Comment by otagi** [comment]
I'm available to help Olivier.
Should I create a new PR for this?

**Comment by toch** [comment]
Cool!

@otagi  no, just add your name as an helper and the pair with olivier in that present one :).

**Comment by toch** [comment]
@apneadiving hijacker! :p

**Comment by otagi** [comment]
@toch I added my name in the master branch (4928170), as this one is out of sync.

**Pull request merged**
