### PR TITLE
Update pair_programming

### PR DESCRIPTION
**Pull request by djouuuuh**
I should mention that I'm only be there on the saturday! I don't know when the session is planned...

### CODE REVIEW

**Comment by toch** [comment]
I think @apneadiving has a good experience with Google Map. @apneadiving am I wrong?

If it is the case, I think it would be a great match.

**Comment by toch** [comment]
@djouuuuh we'll do it on Satursday

**Comment by apneadiving** [comment]
No problemo :)

**Comment by toch** [comment]
Cool! First pair :tada: 

@djouuuuh could you add the following section after `Helpers` section?

``` md

### Pairs

Promotter    | Helpe        | Project                    |
------------ | ------------ | -------------------------- |
@djouuuuh    | @apneadiving | <your project description> |
```

and cross @apneadiving and yourself in respective section? Thanks!

**Comment by djouuuuh** [comment]
@toch Here! Column added.

Edit: Oh, I think I didn't get that in the first place. You wanted a new section at the end. I'll correct my commit.

**Comment by toch** [comment]
Awesome :raised_hands: :shipit:

**Pull request merged**
