### PR TITLE
A suggested Schedule

### PR DESCRIPTION
**Pull request by toch**
Hi @brug-be/rubycamp-2015-participants 

Here a suggested schedule. It will gives us common time to do certain kind of activities, however it's just a suggestion, you do what you want.

One remark: the checkin, checkout, and meal time are the same for everybody.

What do you think?

### CODE REVIEW

**Comment by cveneziani** [comment]
:+1:

**Comment by oana-sipos** [comment]
:+1: @toch good job!

On Wed, Aug 26, 2015 at 2:24 PM, Cecile Veneziani notifications@github.com
wrote:

> [image: :+1:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/brug-be/rubycamp2015/pull/21#issuecomment-134982666.

## 

Be: +32 485 462 660
Ro: +40 743 873 392

oanasipos.wordpress.com

**Comment by norydev** [comment]
good job, yes!

**Comment by borisrorsvort** [comment]
:clap: :clap:

**Comment by cveneziani** [comment]
@toch concerning yoga, it's better to practice it before eating 
(I also prefer running before breakfast :wink: )

**Comment by toch** [comment]
@cveneziani ok, I'll change that.

**Comment by toch** [comment]
so something like
- outdoor
- breakfast
- code
- outdoor
- lunch

?

**Comment by cveneziani** [comment]
I think we can just leave this as is.
It depends on the kind of outdoor activity. 

For instance we may have:
- yoga / running session before breakfast / lunch 
- wandering / freesbie after breakfast / lunch

**Comment by toch** [comment]
As you say, this is just an indication. I merge. Thanks for your feedback!

**Pull request merged**
