### PR TITLE
Add game activity

### PR DESCRIPTION
**Pull request by toch**
@brug-be/rubycamp-2015-participants 

We are several ready to play. To avoid any duplicates and start the discussion, let's share about that!

@djouuuuh could you also organize a werewolf session :)? Thanks!

### CODE REVIEW

**Comment by cveneziani** [comment]
What about Time's Up (no need to buy/bring the original game) and Dominion (I only have French version but can easily translate)?

**Comment by djouuuuh** [comment]
I updated the werewolves section. Is it ok for you @toch ?

**Comment by toch** [comment]
@cveneziani sounds nice. don't hesitate to add them to the list.

@djouuuuh awesome! would it be possible for you to do it after dinner, in the evening?

**Comment by cveneziani** [comment]
I also have [DDR pads](http://static.webshopapp.com/shops/007179/files/005291875/3in1-deluxe-ddr-ignition-dance-mat-v2-for-ps-ps2-x.jpg) and a lot of songs to play with [Stepmania](https://en.wikipedia.org/wiki/StepMania). I'll bring them only if several are interested to play with.

**Comment by djouuuuh** [comment]
@toch yes, all werewolves games must be played after the sunset... gnahahahahaha... Sorry :wolf:

**Comment by ys** [comment]
I can bring some games like:
- Cards against humanity
- exploding kittens

**Comment by toch** [comment]
> Cards against humanity

Nice title!

> exploding kittens

I have one also.

Could you add them to the list? Do you come finally?

**Comment by StanBoyet** [comment]
:+1: for Cards Against Humanity :D

**Comment by ghost** [comment]
I would able to bring my Wii U with mario kart, smash bros, nintendo land and the classic wii sports if there is interest and people would like to play

**Comment by oana-sipos** [comment]
I could also bring 7 Wonders, if anybody is interested in...

Does anybody have Dixit maybe?

**Comment by cveneziani** [comment]
:+1:  for 7 Wonders

**Comment by toch** [comment]
@brug-be/rubycamp-2015-participants I'll merge the PR tonight, as we have a very good start for games. Of course, you can still add (commit) or suggest something (PullRequest) after.

**Pull request merged**
