### PR TITLE
Add react project

### PR DESCRIPTION
**Pull request by StanBoyet**
Create a Tricount-like money management app in React served by a rails API, with a strong emphasis on the feature finding the shortest way to reimburse all participants

Not fixed on the rails API though. Might want to try something new. What about https://github.com/brug-be/rubycamp2015/pull/15 ?

### CODE REVIEW

**Comment by Bluesmile82** [comment]
I will be interested on playing with react or maybe Volt :v:

**Comment by borisrorsvort** [comment]
I might also bring a react project or maybe refactor mycollecto.be with ember 2.0

**Comment by toch** [comment]
@Bluesmile82 and @borisrorsvort if one of you already knows it, could you help @StanBoyet ?

@borisrorsvort could add yourself as a promotter for that project (in another PR)?

**Comment by borisrorsvort** [comment]
Done https://github.com/brug-be/rubycamp2015/pull/17

**Comment by joren** [comment]
+1 would love to learn more about react

**Comment by tgautier** [comment]
I'm :+1: for this one as for the Lotus one #15 

Dunno if it will be at the same time though

**Comment by toch** [comment]
@borisrorsvort knows react. Who else? @joren @tgautier @Bluesmile82 ?

**Comment by tgautier** [comment]
I've never done anything with React, yet! So i'm on the newbie side.

**Comment by toch** [comment]
@joren and @Bluesmile82, is it also your case?

**Comment by joren** [comment]
Sorry, never played with it :(
Would want to learn more :)

**Comment by borisrorsvort** [comment]
I can show you some stuff. Ill try to prepare smth for offline

**Comment by toch** [comment]
I suggest that you do n-tuple programming then.

**Pull request merged**
