### PR TITLE
Update pair_programming.md

### PR DESCRIPTION
**Pull request by ghost**
added to the promotor list

### CODE REVIEW

**Comment by toch** [comment]
@rein-vanimschoot you closed it to fast :)

Let's find a helper for you.

**Comment by toch** [comment]
@flexbox, @tgautier, @apneadiving, @cveneziani, @kvzb is one of you can help @rein-vanimschoot?

**Comment by flexbox** [comment]
@toch @rein-vanimschoot i'm in !

**Comment by toch** [comment]
Cool! Could you add the pair? thanks!

**Pull request merged**
