### PR TITLE
Add new promoter and helper

### PR DESCRIPTION
**Pull request by borisrorsvort**

### CODE REVIEW

**Comment by toch** [comment]
Is there someone interested in helping @borisrorsvort on the following project ?

> Image tagging as a tool for teaching contemporary art

**Comment by StanBoyet** [comment]
Don't know if I could be of help, but I'll follow it seriously, as we use http://annotorious.github.io at work, and it's quite the mess I think.

**Comment by toch** [comment]
It seems you have a pair then :)

**Comment by borisrorsvort** [comment]
:+1:

**Comment by toch** [comment]
@borisrorsvort it's your fork, could you add the pair and fix the conflicts? thanks!

**Comment by StanBoyet** [comment]
@borisrorsvort if you're up for pairing with a junior, I'm up for it !

**Comment by borisrorsvort** [comment]
Sure no prob

**Pull request closed without merging**
