### PR TITLE
Add a pair-programming project using lotus.rb.

### PR DESCRIPTION
**Pull request by kvzb**
And add myself as a helper for other projects.

### CODE REVIEW

**Comment by toch** [comment]
@kvzb I might be interested in doing that with you. Have you a specific goal in mind?

(it will depend if I can help someone or not)

**Comment by nysthee** [comment]
I am interested in following along to see how this framework works.

**Comment by kvzb** [comment]
@toch not really. We could go meta and do a project/photo gallery to showcase the activities of the weekend, something like that.

**Comment by cveneziani** [comment]
I'm also interested to try Lotus.rb

**Comment by toch** [comment]
@kvzb I might have also another idea, and merge both of it: basically it's a list of tweets you will cycle through to tweet it on a regular basis. I like also the idea of a little app for the weekend (or the association in general).

@cveneziani @nysthee you could maybe form a pair, and we can maybe work on the same project?

**Comment by kvzb** [comment]
@toch your idea is interesting! Let's do that

**Comment by nysthee** [comment]
@toch sounds great, what do you think @cveneziani ?

**Comment by cveneziani** [comment]
@nysthee yeah let's form a pair

**Comment by nysthee** [comment]
Maybe @kvzb can update this pull-request to add us all as people doing something with lotus?

**Comment by toch** [comment]
:+1:

**Comment by tgautier** [comment]
:+1: for pair programming on Lotus too

**Comment by toch** [comment]
@tgautier I've merged the PR as two pairs were already formed. I've added you in the promoters list with Lotus project.

Maybe you can create another PR/issue to find a pair?
If you don't find someone, we can do a triplet programming ^^

**Pull request merged**
