### PR TITLE
Rooms: plan and allocation

### PR DESCRIPTION
**Pull request by toch**
Hi @brug-be/rubycamp-2015-participants, for ppl sleeping over

As the checkin is kind of late, I'd like to prepare the allocation before arriving.

So please select a room with the roommate(s) you want.
@oana-sipos and @cveneziani, you have the priority to select. I do not know you're plan, but I certainly do not want to put you in an uncomfortable situation.

There is enough room/space for everybody, let's play it nice.

### CODE REVIEW

**Comment by toch** [comment]
By the way, discuss it here if you're looking for roommate(s), and commit on that branch/PR when you know which room to take.

**Comment by ghost** [comment]
I'm happy to take whatever is left. I don't know anyone yet so it's really all the same to me.

**Comment by cveneziani** [comment]
@toch thanks. Branch updated.

**Comment by StanBoyet** [comment]
I'm gonna stop now :D

**Pull request merged**
