### PR TITLE
Outdoor activities

### PR DESCRIPTION
**Pull request by toch**
@brug-be/rubycamp-2015-participants 

Several suggestions have been made, but in order to make it better, I suggest so pre-organization.

For yoga, I'm a beginner, however I can wrap-up one or two 30 minutes sessions. So if no one is more experienced or want to take over that, I'll organize it.

For Freesbie, we need ... freebie(s). Who can be sure we bring enough?

For running, who can organize it? (check the levels, prepare the way, etc.)

For wandering, who can organize it? (prepare the way)

If you want to organize something, please do it :).

So, just add yourself as participant or organizer or whatever :).

### CODE REVIEW

**Comment by hannesfostie** [comment]
I'll just leave this here: if we decide to do frisbee, I have one of those official extreme frisbee things (175g) (which I can't even properly throw) as well as an "aerobie disk", a disk that can stay in the air way longer than a normal frisbee can.

**Comment by ys** [comment]
For Yoga: https://www.youtube.com/user/yogawithadriene session might be good enough:)

**Comment by toch** [comment]
@ys good idea (anyway this is my main source of inspiration :p)

**Comment by Bluesmile82** [comment]
If someone is interested in playing music or singing I can bring my guitar and a little amp.

**Comment by toch** [comment]
@Bluesmile82 I have played a long time ago guitar. If you can give me a simple riff to follow, I can play and bring my guitar.

**Comment by toch** [comment]
http://www.grsentiers.org/ for wandering

**Comment by ghost** [comment]
@Bluesmile82 I'd be up for some jamming! Dont really play the guitar but I do sing

**Comment by toch** [comment]
@nicefiction as you are runner, maybe you can take the lead on that :)

@Bluesmile82 @rein-vanimschoot seems we can play some music :) I'll check my strings

**Comment by StanBoyet** [comment]
If someone wants to have a morning run (slow pace :grin: ), I'll take my shoes !

**Comment by toch** [comment]
@StanBoyet you should see with @nicefiction

**Comment by cveneziani** [comment]
@StanBoyet @nicefiction Also interested in a slow moring running session (only on sunny morning) :smiley:

**Comment by tgautier** [comment]
Same, I'll take my :athletic_shoe:

**Comment by toch** [comment]
@tgautier @cveneziani @StanBoyet please add yourselves to the running activity then :)

**Comment by toch** [comment]
@cveneziani for yoga, a towel should be enough as a mattress.

@cveneziani @borisrorsvort @oana-sipos I've added two suggestions of a class I tried and enjoyed recently. What do you think?

**Comment by toch** [comment]
@brug-be/rubycamp-2015-participants I'll merge the PR tonight, as we have a very good start for outdoor activities. Of course, you can still add (commit) or suggest something (PullRequest) after.

**Comment by cveneziani** [comment]
@toch I'll trust you for the yoga lessons. I'm a beginner.

**Comment by toch** [comment]
I'm also a beginner. Just practicing it since January (I try to do it every day).

**Comment by borisrorsvort** [comment]
I should be able to give some insights too ;)

**Comment by cveneziani** [comment]
Awesome! Yoga lessons everyday!
So how about a running session before breakfast and a yoga session before lunch?

**Comment by StanBoyet** [comment]
Running before breakfast and yoga before lunch seems great :)

**Comment by borisrorsvort** [comment]
And for those who dont run I have recordings for meditation :)

**Comment by joren** [comment]
Damn, so I have to choose between running and meditating :)

**Comment by cveneziani** [comment]
I think we can finish our running session with a short meditating session (personally I only run for ~30 minutes :stuck_out_tongue: )

**Comment by toch** [comment]
could we have that discussion into #21 please ?

**Pull request merged**
