### PR TITLE
Add some links for gems and deploy

### PR DESCRIPTION
**Pull request by borisrorsvort**

### CODE REVIEW

**Comment by StanBoyet** [comment]
Hey, I highjacked your PR to add a link as well

**Comment by flexbox** [comment]
Did the same as @StanBoyet because :wolf:

**Comment by toch** [comment]
Me too :p

**Comment by otagi** [comment]
We're all pirates today. :)

**Comment by flexbox** [comment]
@borisrorsvort According to me you can proceed to merge :)

**Pull request merged**
